language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_install:
  - cp ./src/config/auth.template.json ./src/config/auth.json
script:
  - ./node_modules/.bin/nyc ts-mocha -p ./tsconfig.json ./**/*.spec.ts 
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls