language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_install:
  - npm install -g mocha
  - npm install -g ts-mocha
script:
  - ./node_modules/.bin/nyc ts-mocha -p ./tsconfig.json ./**/*.spec.ts 
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls