version: 0.0
os: linux
files:
  - source: ./dist
    destination: /home/ubuntu/gbot/
  - source: ./package.json
    destination: /home/ubuntu/gbot/
hooks:
  ApplicationStop:
    - location: ./scripts/stop.sh
      runas: root
  BeforeInstall:
    - location: ./scripts/before_install.sh
      runas: root
  # AfterInstall:
  #   - location: /tmp/after_install.sh
  #     runas: root
  ApplicationStart:
    - location: ./scripts/start.sh
      runas: root