version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/gbot/
hooks:
  ApplicationStop:
    - location: ./stop.sh
      runas: root
  ApplicationStart:
    - location: ./start.sh
      runas: root